openapi: 3.0.1
info:
  title: aprovarPedido
  description: API Definition of aprovarPedido
  version: 1.0.0
servers:
- url: http://localhost:8290/pedido/aprovar
paths:
  /:
    get:
      responses:
        default:
          description: Default response
