openapi: 3.0.1
info:
  title: getAll
  description: API Definition of getAll
  version: 1.0.0
servers:
- url: http://localhost:8290/pedido
paths:
  /:
    get:
      responses:
        default:
          description: Default response
